### PR TITLE
Add port-publishing use case

### PR DESCRIPTION
**Pull request by l-dobrev**
Add a paragraph explaining how to use this image to publish ports on existing containers without recreating them.

### CODE REVIEW

**Comment by ozbillwang** [comment]
Can you change the line `### Getting Started` to `### Example` with consistent statement.

**Comment by l-dobrev** [comment]
How's that?

Also fixed a missing back-slash in the example.
Also changed upper-case arguments to lower-case to match the documentation ```docker run --rm alpine/socat -h```.

**Comment by ozbillwang** [comment]
I can't make it work with `--link example-container=target`, I have replaced `example-container` name to a real one. 

seems `=` can't be used with option `--link`, which docker version you have?

Here is mine:
```
$ docker -v
Docker version 18.03.1-ce, build 9ee9f40
```

**Comment by l-dobrev** [comment]
You are right!
The correct separator was ":" not "=".
I have no excuse for missing that. :(

**Pull request merged**
